apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkin-web
  name: checkin-web
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkin-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: checkin-web
    spec:
      containers:
        - image: gcr.io/alio-development/bitbucket.org/dpoint-dev/dpoint-checkin-portal
          imagePullPolicy: IfNotPresent
          name: checkin-web-container-development
